version: "3.1"

services:
  db:
    build:
      context: .
      dockerfile: MySQL.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: development
      TZ: "Asia/Tokyo"
    restart: always
    ports:
      - "3336:3306"
    volumes:
      - ./db-data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
